version: '2'
services:
  itassetmc-app:
    image: itassetmc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://itassetmc-mysql:3306/itassetmc?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://itassetmc-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://itassetmc-elasticsearch:9200
    ports:
      - 8080:8080
  itassetmc-mysql:
    extends:
      file: mysql.yml
      service: itassetmc-mysql
  itassetmc-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: itassetmc-elasticsearch
